#!/bin/bash
# 📱 Telegram Integration - Quick Reference

echo "🚀 CryptoMagic - Telegram Integration Quick Start"
echo ""
echo "📦 INSTALL DEPENDENCIES:"
echo "   pip install pytz requests"
echo ""
echo "🎯 BASIC USAGE:"
echo "   python3 ethmagic.py -f eth5.txt -v 100000 -n 3"
echo ""
echo "👤 WITH CUSTOM WORKER NAME:"
echo "   python3 ethmagic.py -f eth5.txt -v 100000 -n 3 --worker-name robo1"
echo ""
echo "🌐 24/7 SERVER MODE:"
echo "   nohup python3 ethmagic.py -f eth5.txt -v 100000 -n 8 --worker-name bot1 &"
echo ""
echo "📡 WHAT YOU'LL RECEIVE ON TELEGRAM:"
echo "   ✅ Startup notification (with worker name, config)"
echo "   📊 Daily stats on shutdown (addresses generated, rate, matches)"
echo "   🎉 Instant alert when match found (+ file upload)"
echo ""
echo "⚙️ CLI OPTIONS:"
echo "   -f, --file FILE          Target addresses file (required)"
echo "   -v, --verbose COUNT      Progress update interval [default: 100000]"
echo "   -n, --threads WORKERS    Number of worker processes [default: 2]"
echo "   -r, --report-interval    Throttle live output every N seconds [default: 1]"
echo "   --worker-name NAME       Worker identifier for Telegram [default: CryptoBot]"
echo ""
echo "📚 DOCUMENTATION:"
echo "   TELEGRAM_SETUP.md        - Complete setup guide"
echo "   IMPLEMENTATION_SUMMARY.md - Technical details"
echo ""
echo "✨ KEY FEATURES:"
echo "   • Monitor from anywhere (phone, tablet, computer)"
echo "   • Multiple bots with separate notifications"
echo "   • Real-time match detection"
echo "   • Automatic IST timezone"
echo "   • Zero performance impact"
echo "   • 24/7 unattended operation"
echo ""
echo "🧪 TEST IT:"
echo "   python3 ethmagic.py -f eth5.txt -v 100000 -n 2 --worker-name test-bot"
echo "   (You'll see startup notification in Telegram immediately)"
echo ""
